# ------------------------------
# Configuração de Build
# ------------------------------
[build]
  publish = "."                  # Serve arquivos da raiz (index.html)
  functions = "netlify/functions"
  command = "echo 'No build needed'"

# ------------------------------
# Variáveis de Ambiente
# ------------------------------
[build.environment]
  NODE_VERSION = "20"            # Define a versão do Node para funções Lambda
  # Variáveis sensíveis como FB_PIXEL_ID e FB_ACCESS_TOKEN
  # devem ser adicionadas no painel do Netlify:
  # Site settings → Environment → Environment Variables

# ------------------------------
# Headers para todas as rotas
# ------------------------------
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
