[build]
  publish = "."                   # Serve arquivos da raiz
  command = "echo 'No build needed'"  # Não precisa de build

[functions]
  directory = "netlify/functions"      # Pasta de funções

[build.environment]
  NODE_VERSION = "20"                   # Versão Node usada para funções
